# Generated by Django 3.2.9 on 2022-01-08 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='main_branch',
            field=models.BooleanField(default=False, verbose_name='Main Branch'),
        ),
    ]
