# Generated by Django 3.2.9 on 2022-01-20 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_branch_main_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='branch/%Y__%m__%d/'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='main_branch',
            field=models.BooleanField(default=False),
        ),
    ]
