# Generated by Django 3.2.9 on 2022-01-09 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_address_is_main'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='is_main',
        ),
        migrations.CreateModel(
            name='CustomerAddr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_main', models.BooleanField(default=True, verbose_name='Main_Address')),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='addr_customer', to='accounts.address')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_addr', to='accounts.customer')),
            ],
        ),
    ]
